<?php

use Drupal\Core\Routing\RouteMatchInterface;


function simmanager_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the multi_step module.
    case 'help.page.multi_step':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Multi Step Form') . '</p>';
      return $output;
    break;
  }
}

/**
 * Implements hook_theme().
 */

function simmanager_theme()
{
  $theme = [];

  return $theme;
}
